### ISSUE TITLE
Error deleting containers

### ISSUE THREAD

**Issue by TokinRing** [picluster/picluster#31]
While trying to delete a container (the nginx container) from the container manage page, I received the following error:
> Sent request to the server. Please check the logs and running containers for updated information.
> 
> Stopping: mysql
> Error response from daemon: No such container: nginx

I also noticed that the radio buttons are not working as they should be, only one radio should be selectable at a given time. 

I'm digging into the execution logic for this page and see if I can correct and optimize. My initial research led me here https://stackoverflow.com/questions/596351/how-can-i-know-which-radio-button-is-selected-via-jquery

**Comment by rusher81572** [comment]
How to reproduce the radio button issue? Works for me. 

For nginx, Did you build and create the container? Otherwise that error is expected

**Comment by rusher81572** [comment]
Regarding the main issue where it says stopping mysql when you are trying to control another container, that should be fixed in dev

**Comment by TokinRing** [comment]
I was using a version not up to date and in the wrong repo. After switching to HEAD on the dev branch of this repo, I nuked my containers and images to start new.

I am still having an issue getting docker commands to execute. I've checked my logs with `pm2 logs`, I found the following error:
> 1|agent    | TypeError: Promisify is not a function
> 1|agent    |     at Object.<anonymous> (/opt/picluster/agent/agent.js:19:14)
> 1|agent    |     at Module._compile (module.js:410:26)
> 1|agent    |     at Object.Module._extensions..js (module.js:417:10)
> 1|agent    |     at Module.load (module.js:344:32)
> 1|agent    |     at Function.Module._load (module.js:301:12)
> 1|agent    |     at Object.<anonymous (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:70:21)
> 1|agent    |     at Module._compile (module.js:410:26)
> 1|agent    |     at Object.Module._extensions..js (module.js:417:10)
> 1|agent    |     at Module.load (module.js:344:32)
> 1|agent    |     at Function.Module._load (module.js:301:12)

After looking at the agent.js I found that exec was a child_process promise object. After looking online I found the [child-process-promise](https://www.npmjs.com/package/child-process-promise) package that does just what we're looking for. I'm looking to add this to see if it fixes my problem.

**Comment by TokinRing** [comment]
I've added child-process-promise to agent.js in commit a6b760c. So far I've tested this on ubuntu, but would like feedback on other OSes. I've added a new dependency, so you will need to `npm install` the agent.

**Comment by rusher81572** [comment]
Tested on Raspbian and Alpine. LGTM. Closing.
